//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MSMQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveX Formatter.
        /// </summary>
        internal static string ActiveXFormatter {
            get {
                return ResourceManager.GetString("ActiveXFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label &quot;{0}&quot; references more than one queue. Set the path for the desired queue..
        /// </summary>
        internal static string AmbiguousLabel {
            get {
                return ResourceManager.GetString("AmbiguousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived time is undefined for this message. This message was not created by a call to the Receive method..
        /// </summary>
        internal static string ArrivedTimeNotSet {
            get {
                return ResourceManager.GetString("ArrivedTimeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult interface passed is not valid because it was not created as a result of an asynchronous request on this object..
        /// </summary>
        internal static string AsyncResultInvalid {
            get {
                return ResourceManager.GetString("AsyncResultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine authentication for this message. This message was not created by a call to the Receive method..
        /// </summary>
        internal static string AuthenticationNotSet {
            get {
                return ResourceManager.GetString("AuthenticationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the passed properties are invalid..
        /// </summary>
        internal static string C00E0002 {
            get {
                return ResourceManager.GetString("C00E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue does not exist or you do not have sufficient permissions to perform the operation..
        /// </summary>
        internal static string C00E0003 {
            get {
                return ResourceManager.GetString("C00E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A queue with the same path name already exists..
        /// </summary>
        internal static string C00E0005 {
            get {
                return ResourceManager.GetString("C00E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter was passed to a function..
        /// </summary>
        internal static string C00E0006 {
            get {
                return ResourceManager.GetString("C00E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid handle was passed to the function..
        /// </summary>
        internal static string C00E0007 {
            get {
                return ResourceManager.GetString("C00E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was cancelled before it could be completed..
        /// </summary>
        internal static string C00E0008 {
            get {
                return ResourceManager.GetString("C00E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing violation resulted from queue being open already for exclusive receive..
        /// </summary>
        internal static string C00E0009 {
            get {
                return ResourceManager.GetString("C00E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Queue service is not available..
        /// </summary>
        internal static string C00E000B {
            get {
                return ResourceManager.GetString("C00E000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find specified machine..
        /// </summary>
        internal static string C00E000D {
            get {
                return ResourceManager.GetString("C00E000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort specified in MQLocateBegin is invalid. There may be duplicate columns..
        /// </summary>
        internal static string C00E0010 {
            get {
                return ResourceManager.GetString("C00E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is invalid..
        /// </summary>
        internal static string C00E0011 {
            get {
                return ResourceManager.GetString("C00E0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection with Active Directory cannot be established. Verify that there are sufficient permissions to perform this operation..
        /// </summary>
        internal static string C00E0013 {
            get {
                return ResourceManager.GetString("C00E0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid queue path name..
        /// </summary>
        internal static string C00E0014 {
            get {
                return ResourceManager.GetString("C00E0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property value..
        /// </summary>
        internal static string C00E0018 {
            get {
                return ResourceManager.GetString("C00E0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid VARTYPE value..
        /// </summary>
        internal static string C00E0019 {
            get {
                return ResourceManager.GetString("C00E0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer supplied to MQReceiveMessage for reading the message body was too small. The message cannot be removed from the queue, and the message body was truncated to fit the buffer when it was copied to the buffer..
        /// </summary>
        internal static string C00E001A {
            get {
                return ResourceManager.GetString("C00E001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout for the requested operation has expired..
        /// </summary>
        internal static string C00E001B {
            get {
                return ResourceManager.GetString("C00E001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ_ACTION_PEEK_NEXT specified to MQReceiveMessage cannot be used with the current cursor position..
        /// </summary>
        internal static string C00E001C {
            get {
                return ResourceManager.GetString("C00E001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message that the cursor is currently pointing to has been removed from the queue by another process or by another call to Receive without the use of this cursor..
        /// </summary>
        internal static string C00E001D {
            get {
                return ResourceManager.GetString("C00E001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format name is invalid..
        /// </summary>
        internal static string C00E001E {
            get {
                return ResourceManager.GetString("C00E001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format name buffer supplied to the API was too small to fit the format name..
        /// </summary>
        internal static string C00E001F {
            get {
                return ResourceManager.GetString("C00E001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified format name does not support the requested operation. For example, a direct queue format name cannot be deleted..
        /// </summary>
        internal static string C00E0020 {
            get {
                return ResourceManager.GetString("C00E0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security descriptor is not valid..
        /// </summary>
        internal static string C00E0021 {
            get {
                return ResourceManager.GetString("C00E0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer supplied for the user identifier property is too small..
        /// </summary>
        internal static string C00E0022 {
            get {
                return ResourceManager.GetString("C00E0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer passed to MQGetQueueSecurity is too small..
        /// </summary>
        internal static string C00E0023 {
            get {
                return ResourceManager.GetString("C00E0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security credentials cannot be verified because the Remote Procedure Call (RPC) server cannot reproduce the client application..
        /// </summary>
        internal static string C00E0024 {
            get {
                return ResourceManager.GetString("C00E0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Message Queuing system is denied..
        /// </summary>
        internal static string C00E0025 {
            get {
                return ResourceManager.GetString("C00E0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client does not have the required privileges to perform the operation..
        /// </summary>
        internal static string C00E0026 {
            get {
                return ResourceManager.GetString("C00E0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient resources to perform operation..
        /// </summary>
        internal static string C00E0027 {
            get {
                return ResourceManager.GetString("C00E0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process request because the user buffer is too small to hold the information returned by the request..
        /// </summary>
        internal static string C00E0028 {
            get {
                return ResourceManager.GetString("C00E0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store recoverable or journal message. The corresponding message was not sent..
        /// </summary>
        internal static string C00E002A {
            get {
                return ResourceManager.GetString("C00E002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer supplied for the user certificate property is too small..
        /// </summary>
        internal static string C00E002B {
            get {
                return ResourceManager.GetString("C00E002B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User certificate is not valid..
        /// </summary>
        internal static string C00E002C {
            get {
                return ResourceManager.GetString("C00E002C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Message Queuing certificate is corrupted..
        /// </summary>
        internal static string C00E002D {
            get {
                return ResourceManager.GetString("C00E002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s internal Message Queuing certificate does not exist..
        /// </summary>
        internal static string C00E002F {
            get {
                return ResourceManager.GetString("C00E002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic function has failed..
        /// </summary>
        internal static string C00E0030 {
            get {
                return ResourceManager.GetString("C00E0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption operations are not supported by the computer..
        /// </summary>
        internal static string C00E0033 {
            get {
                return ResourceManager.GetString("C00E0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security context is unrecognized..
        /// </summary>
        internal static string C00E0035 {
            get {
                return ResourceManager.GetString("C00E0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve SID information from the thread token..
        /// </summary>
        internal static string C00E0036 {
            get {
                return ResourceManager.GetString("C00E0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve user account information..
        /// </summary>
        internal static string C00E0037 {
            get {
                return ResourceManager.GetString("C00E0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQCOLUMNS parameter is invalid..
        /// </summary>
        internal static string C00E0038 {
            get {
                return ResourceManager.GetString("C00E0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid propid value..
        /// </summary>
        internal static string C00E0039 {
            get {
                return ResourceManager.GetString("C00E0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid relation value in restriction..
        /// </summary>
        internal static string C00E003A {
            get {
                return ResourceManager.GetString("C00E003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property buffer size..
        /// </summary>
        internal static string C00E003B {
            get {
                return ResourceManager.GetString("C00E003B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid propid value in MQRESTRICTION parameter..
        /// </summary>
        internal static string C00E003C {
            get {
                return ResourceManager.GetString("C00E003C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MQQUEUEPROPS parameter. It is either null or has zero properties..
        /// </summary>
        internal static string C00E003D {
            get {
                return ResourceManager.GetString("C00E003D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid propid supplied for the requested Operation..
        /// </summary>
        internal static string C00E003E {
            get {
                return ResourceManager.GetString("C00E003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required properties for the operation were not all specified in the input parameters..
        /// </summary>
        internal static string C00E003F {
            get {
                return ResourceManager.GetString("C00E003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MSMQ Configuration (msmq) object already exists in Active Directory..
        /// </summary>
        internal static string C00E0040 {
            get {
                return ResourceManager.GetString("C00E0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MQQMPROPS parameter. It is either null or has zero properties..
        /// </summary>
        internal static string C00E0041 {
            get {
                return ResourceManager.GetString("C00E0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS is full..
        /// </summary>
        internal static string C00E0042 {
            get {
                return ResourceManager.GetString("C00E0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal DS error has occurred..
        /// </summary>
        internal static string C00E0043 {
            get {
                return ResourceManager.GetString("C00E0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object owner was invalid. For example, MQCreateQueue failed because the Queue Manager object is invalid..
        /// </summary>
        internal static string C00E0044 {
            get {
                return ResourceManager.GetString("C00E0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified access mode is not supported..
        /// </summary>
        internal static string C00E0045 {
            get {
                return ResourceManager.GetString("C00E0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer supplied for the result is too small..
        /// </summary>
        internal static string C00E0046 {
            get {
                return ResourceManager.GetString("C00E0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Network is in use and cannot be deleted..
        /// </summary>
        internal static string C00E0048 {
            get {
                return ResourceManager.GetString("C00E0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object owner has not responded..
        /// </summary>
        internal static string C00E0049 {
            get {
                return ResourceManager.GetString("C00E0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object owner is not reachable..
        /// </summary>
        internal static string C00E004A {
            get {
                return ResourceManager.GetString("C00E004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs when reading from a queue on a remote computer..
        /// </summary>
        internal static string C00E004B {
            get {
                return ResourceManager.GetString("C00E004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to connect to MS DTC..
        /// </summary>
        internal static string C00E004C {
            get {
                return ResourceManager.GetString("C00E004C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import the transaction..
        /// </summary>
        internal static string C00E004E {
            get {
                return ResourceManager.GetString("C00E004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction usage is invalid..
        /// </summary>
        internal static string C00E0050 {
            get {
                return ResourceManager.GetString("C00E0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction operations sequence is invalid..
        /// </summary>
        internal static string C00E0051 {
            get {
                return ResourceManager.GetString("C00E0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectorType was not supplied. The connector type is required to send acknowledgment or secure messages..
        /// </summary>
        internal static string C00E0055 {
            get {
                return ResourceManager.GetString("C00E0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Queue manager service has been restarted. The queue handle is stale and should be closed..
        /// </summary>
        internal static string C00E0056 {
            get {
                return ResourceManager.GetString("C00E0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enlist the transaction..
        /// </summary>
        internal static string C00E0058 {
            get {
                return ResourceManager.GetString("C00E0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue handle can no longer be used to receive messages because the queue was deleted. The handle should be closed..
        /// </summary>
        internal static string C00E005A {
            get {
                return ResourceManager.GetString("C00E005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context Parameter(MQLocateBegin)..
        /// </summary>
        internal static string C00E005B {
            get {
                return ResourceManager.GetString("C00E005B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid propid value in MQSORTSET..
        /// </summary>
        internal static string C00E005C {
            get {
                return ResourceManager.GetString("C00E005C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label size is too big. It should be less than or equal to MQ_MAX_MSG_LABEL_LEN..
        /// </summary>
        internal static string C00E005D {
            get {
                return ResourceManager.GetString("C00E005D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label buffer supplied to the API was too small..
        /// </summary>
        internal static string C00E005E {
            get {
                return ResourceManager.GetString("C00E005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry list of MQIS servers is empty..
        /// </summary>
        internal static string C00E005F {
            get {
                return ResourceManager.GetString("C00E005F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQIS database is in read-only mode..
        /// </summary>
        internal static string C00E0060 {
            get {
                return ResourceManager.GetString("C00E0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer supplied for the symmetric key property is too small..
        /// </summary>
        internal static string C00E0061 {
            get {
                return ResourceManager.GetString("C00E0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer supplied for the signature property is too small..
        /// </summary>
        internal static string C00E0062 {
            get {
                return ResourceManager.GetString("C00E0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The buffer passed for the Provider name property is too small..
        /// </summary>
        internal static string C00E0063 {
            get {
                return ResourceManager.GetString("C00E0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign message queuing system does not support the operation..
        /// </summary>
        internal static string C00E0064 {
            get {
                return ResourceManager.GetString("C00E0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database does not currently allow write operations because another MQIS server is being installed..
        /// </summary>
        internal static string C00E0065 {
            get {
                return ResourceManager.GetString("C00E0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ independent clients cannot serve MSMQ dependent clients..
        /// </summary>
        internal static string C00E0066 {
            get {
                return ResourceManager.GetString("C00E0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Queuing server has reached the maximum number of dependent clients it can serve..
        /// </summary>
        internal static string C00E0067 {
            get {
                return ResourceManager.GetString("C00E0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization file for queue {1} in LQS was deleted because it was corrupted..
        /// </summary>
        internal static string C00E0068 {
            get {
                return ResourceManager.GetString("C00E0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote computer is not available..
        /// </summary>
        internal static string C00E0069 {
            get {
                return ResourceManager.GetString("C00E0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A workgroup installation computer does not support the operation..
        /// </summary>
        internal static string C00E006A {
            get {
                return ResourceManager.GetString("C00E006A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cryptographic Service Provider is not supported by Message Queuing..
        /// </summary>
        internal static string C00E006B {
            get {
                return ResourceManager.GetString("C00E006B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the Security descriptor for the cryptographic keys..
        /// </summary>
        internal static string C00E006C {
            get {
                return ResourceManager.GetString("C00E006C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user attempted to send an authenticated message without a certificate. .
        /// </summary>
        internal static string C00E006D {
            get {
                return ResourceManager.GetString("C00E006D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column PROPID_Q_PATHNAME_DNS is not supported for the MQLocateBegin API..
        /// </summary>
        internal static string C00E006E {
            get {
                return ResourceManager.GetString("C00E006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a certificate store for the internal certificate..
        /// </summary>
        internal static string C00E006F {
            get {
                return ResourceManager.GetString("C00E006F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open a certificate store for the internal certificate..
        /// </summary>
        internal static string C00E0070 {
            get {
                return ResourceManager.GetString("C00E0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQServices object does not support the operation..
        /// </summary>
        internal static string C00E0071 {
            get {
                return ResourceManager.GetString("C00E0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to grant the Add Guid permission to the current user..
        /// </summary>
        internal static string C00E0072 {
            get {
                return ResourceManager.GetString("C00E0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQOCM.DLL library cannot be loaded..
        /// </summary>
        internal static string C00E0073 {
            get {
                return ResourceManager.GetString("C00E0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point in the MSMQOCM.DLL library cannot be located..
        /// </summary>
        internal static string C00E0074 {
            get {
                return ResourceManager.GetString("C00E0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find Message Queuing servers on the domain controllers..
        /// </summary>
        internal static string C00E0075 {
            get {
                return ResourceManager.GetString("C00E0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer joined the domain, but Message Queuing will continue to run in workgroup mode because it failed to register itself in Active Directory..
        /// </summary>
        internal static string C00E0076 {
            get {
                return ResourceManager.GetString("C00E0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an object on a specified Global Catalog server..
        /// </summary>
        internal static string C00E0077 {
            get {
                return ResourceManager.GetString("C00E0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create msmqConfiguration object with GUID that matched computer installation. You must uninstall Message Queuing and then reinstall it..
        /// </summary>
        internal static string C00E0078 {
            get {
                return ResourceManager.GetString("C00E0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key for the computer cannot be found..
        /// </summary>
        internal static string C00E0079 {
            get {
                return ResourceManager.GetString("C00E0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key for the computer does not exist..
        /// </summary>
        internal static string C00E007A {
            get {
                return ResourceManager.GetString("C00E007A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQPRIVATEPROPS parameter value is invalid. This might be because it has a null value or has zero properties specified..
        /// </summary>
        internal static string C00E007B {
            get {
                return ResourceManager.GetString("C00E007B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Global Catalog servers in the specified domain..
        /// </summary>
        internal static string C00E007C {
            get {
                return ResourceManager.GetString("C00E007C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Message Queuing servers on the Global Catalog domain controllers..
        /// </summary>
        internal static string C00E007D {
            get {
                return ResourceManager.GetString("C00E007D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the distinguished name of the local computer..
        /// </summary>
        internal static string C00E007E {
            get {
                return ResourceManager.GetString("C00E007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot hash Data for an authenticated message..
        /// </summary>
        internal static string C00E007F {
            get {
                return ResourceManager.GetString("C00E007F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign data for an authenticated message before it was sent..
        /// </summary>
        internal static string C00E0080 {
            get {
                return ResourceManager.GetString("C00E0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create hash object for an authenticated message..
        /// </summary>
        internal static string C00E0081 {
            get {
                return ResourceManager.GetString("C00E0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of a received message is not valid..
        /// </summary>
        internal static string C00E0082 {
            get {
                return ResourceManager.GetString("C00E0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing any messages from queue {0}..
        /// </summary>
        internal static string ClearingQueue {
            get {
                return ResourceManager.GetString("ClearingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify coercion type for serialized objects using this formatter..
        /// </summary>
        internal static string CoertionType {
            get {
                return ResourceManager.GetString("CoertionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve name {0} (error = {1} )..
        /// </summary>
        internal static string CouldntResolve {
            get {
                return ResourceManager.GetString("CouldntResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve name {0}..
        /// </summary>
        internal static string CouldntResolveName {
            get {
                return ResourceManager.GetString("CouldntResolveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating queue {0}..
        /// </summary>
        internal static string CreatingQueue {
            get {
                return ResourceManager.GetString("CreatingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria property has not been defined..
        /// </summary>
        internal static string CriteriaNotDefined {
            get {
                return ResourceManager.GetString("CriteriaNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size is invalid. It must be greater than or equal to zero..
        /// </summary>
        internal static string DefaultSizeError {
            get {
                return ResourceManager.GetString("DefaultSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting queue {0}..
        /// </summary>
        internal static string DeletingQueue {
            get {
                return ResourceManager.GetString("DeletingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination queue is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string DestinationQueueNotSet {
            get {
                return ResourceManager.GetString("DestinationQueueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a formatter capable of reading this message..
        /// </summary>
        internal static string FormatterMissing {
            get {
                return ResourceManager.GetString("FormatterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier for this message is not defined. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string IdNotSet {
            get {
                return ResourceManager.GetString("IdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path property must be set to create an installer for this MessageQueue..
        /// </summary>
        internal static string IncompleteMQ {
            get {
                return ResourceManager.GetString("IncompleteMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote an incorrect number of bytes..
        /// </summary>
        internal static string IncorrectNumberOfBytes {
            get {
                return ResourceManager.GetString("IncorrectNumberOfBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        internal static string InfiniteValue {
            get {
                return ResourceManager.GetString("InfiniteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid. It must be between {0} and {1}..
        /// </summary>
        internal static string InvalidDateValue {
            get {
                return ResourceManager.GetString("InvalidDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier is not in the incorrect format..
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find queue with label {0}..
        /// </summary>
        internal static string InvalidLabel {
            get {
                return ResourceManager.GetString("InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Journal size has to be greater than or equal to 0..
        /// </summary>
        internal static string InvalidMaxJournalSize {
            get {
                return ResourceManager.GetString("InvalidMaxJournalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Journal size has to be greater than or equal to 0..
        /// </summary>
        internal static string InvalidMaxQueueSize {
            get {
                return ResourceManager.GetString("InvalidMaxQueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value {1} for parameter {0}..
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value {1} for property {0}..
        /// </summary>
        internal static string InvalidProperty {
            get {
                return ResourceManager.GetString("InvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a queue with the path {0}..
        /// </summary>
        internal static string InvalidQueuePathToCreate {
            get {
                return ResourceManager.GetString("InvalidQueuePathToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustee property of an entry in the access control list is null..
        /// </summary>
        internal static string InvalidTrustee {
            get {
                return ResourceManager.GetString("InvalidTrustee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry in the access control list contains a trustee with an invalid name..
        /// </summary>
        internal static string InvalidTrusteeName {
            get {
                return ResourceManager.GetString("InvalidTrusteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize the message passed as an argument. Cannot recognize the serialization format..
        /// </summary>
        internal static string InvalidTypeDeserialization {
            get {
                return ResourceManager.GetString("InvalidTypeDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize the object because its type is not supported..
        /// </summary>
        internal static string InvalidTypeSerialization {
            get {
                return ResourceManager.GetString("InvalidTypeSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML format is invalid..
        /// </summary>
        internal static string InvalidXmlFormat {
            get {
                return ResourceManager.GetString("InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name is too long. Size of queue name cannot exceed 255 characters..
        /// </summary>
        internal static string LongQueueName {
            get {
                return ResourceManager.GetString("LongQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup identifier is not defined for this message. The message was not created by a call to the Receive method, or lookup identifier was not added to the properties to retrieve..
        /// </summary>
        internal static string LookupIdNotSet {
            get {
                return ResourceManager.GetString("LookupIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message requested was not found in the queue specified..
        /// </summary>
        internal static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Queue Browser.
        /// </summary>
        internal static string MessageQueueBrowser {
            get {
                return ResourceManager.GetString("MessageQueueBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to a queue on a Message Queue server..
        /// </summary>
        internal static string MessageQueueDesc {
            get {
                return ResourceManager.GetString("MessageQueueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string MessageTypeNotSet {
            get {
                return ResourceManager.GetString("MessageTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} was not retrieved when receiving the message. Ensure that the PropertyFilter is set correctly..
        /// </summary>
        internal static string MissingProperty {
            get {
                return ResourceManager.GetString("MissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether or not the queue only accepts authenticated messages..
        /// </summary>
        internal static string MQ_Authenticate {
            get {
                return ResourceManager.GetString("MQ_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for routing the queue&apos;s messages over the network..
        /// </summary>
        internal static string MQ_BasePriority {
            get {
                return ResourceManager.GetString("MQ_BasePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the queue has read permission..
        /// </summary>
        internal static string MQ_CanRead {
            get {
                return ResourceManager.GetString("MQ_CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the queue has write permission..
        /// </summary>
        internal static string MQ_CanWrite {
            get {
                return ResourceManager.GetString("MQ_CanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to categorize their queues according to how they are used..
        /// </summary>
        internal static string MQ_Category {
            get {
                return ResourceManager.GetString("MQ_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the time and date when the queue was created..
        /// </summary>
        internal static string MQ_CreateTime {
            get {
                return ResourceManager.GetString("MQ_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the properties that are going to be used by default when sending messages to the queue referenced by this object..
        /// </summary>
        internal static string MQ_DefaultPropertiesToSend {
            get {
                return ResourceManager.GetString("MQ_DefaultPropertiesToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, no other instance of this object will be able to receive messages..
        /// </summary>
        internal static string MQ_DenySharedReceive {
            get {
                return ResourceManager.GetString("MQ_DenySharedReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether or not the queue only accepts non-private (clear) messages..
        /// </summary>
        internal static string MQ_EncryptionRequired {
            get {
                return ResourceManager.GetString("MQ_EncryptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a unique name for the queue generated by MSMQ when it is created..
        /// </summary>
        internal static string MQ_FormatName {
            get {
                return ResourceManager.GetString("MQ_FormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the formatter that will be used when an object is written to or read from the body..
        /// </summary>
        internal static string MQ_Formatter {
            get {
                return ResourceManager.GetString("MQ_Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies a specific public queue..
        /// </summary>
        internal static string MQ_GuidId {
            get {
                return ResourceManager.GetString("MQ_GuidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a description of the queue..
        /// </summary>
        internal static string MQ_Label {
            get {
                return ResourceManager.GetString("MQ_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the last time the properties of a queue were modified..
        /// </summary>
        internal static string MQ_LastModifyTime {
            get {
                return ResourceManager.GetString("MQ_LastModifyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the machine where the queue referenced by this object is located..
        /// </summary>
        internal static string MQ_MachineName {
            get {
                return ResourceManager.GetString("MQ_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the maximum size (in kilobytes) of the journal queue. Use &quot;Infinity&quot; to set the maximum value..
        /// </summary>
        internal static string MQ_MaximumJournalSize {
            get {
                return ResourceManager.GetString("MQ_MaximumJournalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the maximum size (in kilobytes) of the queue. Use &quot;Infinity&quot; to set the maximum value..
        /// </summary>
        internal static string MQ_MaximumQueueSize {
            get {
                return ResourceManager.GetString("MQ_MaximumQueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the property filter used by this queue to receive messages..
        /// </summary>
        internal static string MQ_MessageReadPropertyFilter {
            get {
                return ResourceManager.GetString("MQ_MessageReadPropertyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the IP multicast address associated with the queue..
        /// </summary>
        internal static string MQ_MulticastAddress {
            get {
                return ResourceManager.GetString("MQ_MulticastAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the location of the queue that will be referenced by this object..
        /// </summary>
        internal static string MQ_Path {
            get {
                return ResourceManager.GetString("MQ_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event occurs when a message is read without being removed from the queue using the BeginPeek method..
        /// </summary>
        internal static string MQ_PeekCompleted {
            get {
                return ResourceManager.GetString("MQ_PeekCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the friendly name that identifies the queue referenced by this object..
        /// </summary>
        internal static string MQ_QueueName {
            get {
                return ResourceManager.GetString("MQ_QueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native handle used to receive messages from the message queue..
        /// </summary>
        internal static string MQ_ReadHandle {
            get {
                return ResourceManager.GetString("MQ_ReadHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event occurs when a message is removed from the queue using the BeginReceive method..
        /// </summary>
        internal static string MQ_ReceiveCompleted {
            get {
                return ResourceManager.GetString("MQ_ReceiveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object used to marshal the event handler calls issued as a result of a BeginReceive or BeginPeek request..
        /// </summary>
        internal static string MQ_SynchronizingObject {
            get {
                return ResourceManager.GetString("MQ_SynchronizingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a queue is transactional, it can only accept messages that are sent as part of a transaction..
        /// </summary>
        internal static string MQ_Transactional {
            get {
                return ResourceManager.GetString("MQ_Transactional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if messages retrieved from the queue are also copied to its journal queue..
        /// </summary>
        internal static string MQ_UseJournalQueue {
            get {
                return ResourceManager.GetString("MQ_UseJournalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native handle used to send messages to the message queue..
        /// </summary>
        internal static string MQ_WriteHandle {
            get {
                return ResourceManager.GetString("MQ_WriteHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the classification of acknowledgment that this message represents..
        /// </summary>
        internal static string MsgAcknowledgement {
            get {
                return ResourceManager.GetString("MsgAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of acknowledgment messages the system posts (in the administration queue) and when acknowledgments are returned..
        /// </summary>
        internal static string MsgAcknowledgeType {
            get {
                return ResourceManager.GetString("MsgAcknowledgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the administration queue used for system-generated acknowledgment..
        /// </summary>
        internal static string MsgAdministrationQueue {
            get {
                return ResourceManager.GetString("MsgAdministrationQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies application-generated information such as single integer values or application-defined message classes..
        /// </summary>
        internal static string MsgAppSpecific {
            get {
                return ResourceManager.GetString("MsgAppSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates when the message arrived at the queue..
        /// </summary>
        internal static string MsgArrivedTime {
            get {
                return ResourceManager.GetString("MsgArrivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if the SenderId is to be or has been attached to the message..
        /// </summary>
        internal static string MsgAttachSenderId {
            get {
                return ResourceManager.GetString("MsgAttachSenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by the receiving application when trying to determine if authentication was requested. If authentication was requested and the message is in the queue, then the message was authenticated..
        /// </summary>
        internal static string MsgAuthenticated {
            get {
                return ResourceManager.GetString("MsgAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of the cryptographic provider used to generate the digital signature of the message..
        /// </summary>
        internal static string MsgAuthenticationProviderName {
            get {
                return ResourceManager.GetString("MsgAuthenticationProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of cryptographic provider used to generate the digital signature of the message..
        /// </summary>
        internal static string MsgAuthenticationProviderType {
            get {
                return ResourceManager.GetString("MsgAuthenticationProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the information included in the body of the message..
        /// </summary>
        internal static string MsgBody {
            get {
                return ResourceManager.GetString("MsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the information included in the body of the message..
        /// </summary>
        internal static string MsgBodyStream {
            get {
                return ResourceManager.GetString("MsgBodyStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the type of body the message contains.
        /// </summary>
        internal static string MsgBodyType {
            get {
                return ResourceManager.GetString("MsgBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever a message is passed by a connector application, the connector type is required so that the sending and receiving applications know how to interpret the security and acknowledgment properties of the messages. When sending application-encrypted messages, this property tells the MSMQ runtime to use the symmetric key..
        /// </summary>
        internal static string MsgConnectorType {
            get {
                return ResourceManager.GetString("MsgConnectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides an application-defined identifier that the receiving application can use to sort messages..
        /// </summary>
        internal static string MsgCorrelationId {
            get {
                return ResourceManager.GetString("MsgCorrelationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default body buffer size to create, when the message is received..
        /// </summary>
        internal static string MsgDefaultBodySize {
            get {
                return ResourceManager.GetString("MsgDefaultBodySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default extension buffer size to create, when the message is received..
        /// </summary>
        internal static string MsgDefaultExtensionSize {
            get {
                return ResourceManager.GetString("MsgDefaultExtensionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default label buffer size to create, when the message is received..
        /// </summary>
        internal static string MsgDefaultLabelSize {
            get {
                return ResourceManager.GetString("MsgDefaultLabelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the original destination queue of a message..
        /// </summary>
        internal static string MsgDestinationQueue {
            get {
                return ResourceManager.GetString("MsgDestinationQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the symmetric key used to encrypt messages. Is required when you send application-encrypted messages..
        /// </summary>
        internal static string MsgDestinationSymmetricKey {
            get {
                return ResourceManager.GetString("MsgDestinationSymmetricKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the digital signature used to authenticate the message..
        /// </summary>
        internal static string MsgDigitalSignature {
            get {
                return ResourceManager.GetString("MsgDigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the encryption algorithm used to encrypt the message body of a private message..
        /// </summary>
        internal static string MsgEncryptionAlgorithm {
            get {
                return ResourceManager.GetString("MsgEncryptionAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a place to put additional application-defined information that is associated with the message..
        /// </summary>
        internal static string MsgExtension {
            get {
                return ResourceManager.GetString("MsgExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the hashing algorithm MSMQ uses when authenticating messages..
        /// </summary>
        internal static string MsgHashAlgorithm {
            get {
                return ResourceManager.GetString("MsgHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the MSMQ-generated identifier of the message..
        /// </summary>
        internal static string MsgId {
            get {
                return ResourceManager.GetString("MsgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is used by receiving applications to verify that a message was the first message sent in a single transaction to a single queue..
        /// </summary>
        internal static string MsgIsFirstInTransaction {
            get {
                return ResourceManager.GetString("MsgIsFirstInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is used by receiving applications to verify that a message was the last message sent from a single transaction to a single queue..
        /// </summary>
        internal static string MsgIsLastInTransaction {
            get {
                return ResourceManager.GetString("MsgIsLastInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the label of the message..
        /// </summary>
        internal static string MsgLabel {
            get {
                return ResourceManager.GetString("MsgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the MSMQ-generated lookup identifier of the message..
        /// </summary>
        internal static string MsgLookupId {
            get {
                return ResourceManager.GetString("MsgLookupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message can be a normal MSMQ message, a positive or negative (arrival and read) acknowledgment message, or a report message..
        /// </summary>
        internal static string MsgMessageType {
            get {
                return ResourceManager.GetString("MsgMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message priority affects how MSMQ handles the message while it is in route, as well as where the message is placed in the queue..
        /// </summary>
        internal static string MsgPriority {
            get {
                return ResourceManager.GetString("MsgPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message will be delivered, even if a computer crashes while the message is en-route to the queue..
        /// </summary>
        internal static string MsgRecoverable {
            get {
                return ResourceManager.GetString("MsgRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the queue to which application-generated response messages are returned..
        /// </summary>
        internal static string MsgResponseQueue {
            get {
                return ResourceManager.GetString("MsgResponseQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the security certificate used to authenticate messages..
        /// </summary>
        internal static string MsgSenderCertificate {
            get {
                return ResourceManager.GetString("MsgSenderCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is set by MSMQ, and is used primarily by the receiving Queue Manager when authenticating a message..
        /// </summary>
        internal static string MsgSenderId {
            get {
                return ResourceManager.GetString("MsgSenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the version of MSMQ used to send the message..
        /// </summary>
        internal static string MsgSenderVersion {
            get {
                return ResourceManager.GetString("MsgSenderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the date and time that the message was sent by the source Queue Manager..
        /// </summary>
        internal static string MsgSentTime {
            get {
                return ResourceManager.GetString("MsgSentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the computer where the message originated..
        /// </summary>
        internal static string MsgSourceMachine {
            get {
                return ResourceManager.GetString("MsgSourceMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total time (in seconds) the message is allowed to live. Use &quot;Infinity&quot; to set the maximum value..
        /// </summary>
        internal static string MsgTimeToBeReceived {
            get {
                return ResourceManager.GetString("MsgTimeToBeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a time limit (in seconds) for the message to reach the queue. Use &quot;Infinity&quot; to set the maximum value..
        /// </summary>
        internal static string MsgTimeToReachQueue {
            get {
                return ResourceManager.GetString("MsgTimeToReachQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the top (root) object of a graph is laid out in the serialized stream..
        /// </summary>
        internal static string MsgTopObjectFormat {
            get {
                return ResourceManager.GetString("MsgTopObjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is used by receiving applications to verify that a message was sent from a specific transaction..
        /// </summary>
        internal static string MsgTransactionId {
            get {
                return ResourceManager.GetString("MsgTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the transaction status queue on the source computer..
        /// </summary>
        internal static string MsgTransactionStatusQueue {
            get {
                return ResourceManager.GetString("MsgTransactionStatusQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how type descriptions are laid out in the serialized stream..
        /// </summary>
        internal static string MsgTypeFormat {
            get {
                return ResourceManager.GetString("MsgTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the message needs to be authenticated..
        /// </summary>
        internal static string MsgUseAuthentication {
            get {
                return ResourceManager.GetString("MsgUseAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if a copy of the message should be sent to a dead-letter queue..
        /// </summary>
        internal static string MsgUseDeadLetterQueue {
            get {
                return ResourceManager.GetString("MsgUseDeadLetterQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this property to have MSMQ encrypt a private message..
        /// </summary>
        internal static string MsgUseEncryption {
            get {
                return ResourceManager.GetString("MsgUseEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if a copy of the message should be kept in a machine journal (on the originating machine)..
        /// </summary>
        internal static string MsgUseJournalQueue {
            get {
                return ResourceManager.GetString("MsgUseJournalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if report messages are sent when tracing a message..
        /// </summary>
        internal static string MsgUseTracing {
            get {
                return ResourceManager.GetString("MsgUseTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing private queues is not supported by the Microsoft Message Queuing (MSMQ) runtime installed on this computer..
        /// </summary>
        internal static string MSMQInfoNotSupported {
            get {
                return ResourceManager.GetString("MSMQInfoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Queuing has not been installed on this computer..
        /// </summary>
        internal static string MSMQNotInstalled {
            get {
                return ResourceManager.GetString("MSMQNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor is not currently pointing to a Message instance. It is located either before the first or after the last message in the enumeration..
        /// </summary>
        internal static string NoCurrentMessage {
            get {
                return ResourceManager.GetString("NoCurrentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor is not currently pointing to a MessageQueue instance. It is located either before the first or after the last queue in the enumeration..
        /// </summary>
        internal static string NoCurrentMessageQueue {
            get {
                return ResourceManager.GetString("NoCurrentMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property because the message is not an acknowledgment message..
        /// </summary>
        internal static string NotAcknowledgement {
            get {
                return ResourceManager.GetString("NotAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageQueueInstaller cannot install the component. MessageQueue installer can only install MessageQueue components..
        /// </summary>
        internal static string NotAMessageQueue {
            get {
                return ResourceManager.GetString("NotAMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature is not implemented..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not Set].
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS path name for the queue specified is not available..
        /// </summary>
        internal static string PathNameDns {
            get {
                return ResourceManager.GetString("PathNameDns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed because the path was not set..
        /// </summary>
        internal static string PathNotSet {
            get {
                return ResourceManager.GetString("PathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path syntax is invalid..
        /// </summary>
        internal static string PathSyntax {
            get {
                return ResourceManager.GetString("PathSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the following properties (Path, FormatName, MachineName, Label, or Category) must be set as permission entry criteria..
        /// </summary>
        internal static string PermissionAllNull {
            get {
                return ResourceManager.GetString("PermissionAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path, FormatName, MachineName, Label, or Category cannot be set simultaneously as a single permission entry criteria..
        /// </summary>
        internal static string PermissionPathOrCriteria {
            get {
                return ResourceManager.GetString("PermissionPathOrCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested operation is not supported on this platform..
        /// </summary>
        internal static string PlatformNotSupported {
            get {
                return ResourceManager.GetString("PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while locating machines..
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has not been added..
        /// </summary>
        internal static string PropertyAddFailed {
            get {
                return ResourceManager.GetString("PropertyAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property overflow..
        /// </summary>
        internal static string PropertyOverflow {
            get {
                return ResourceManager.GetString("PropertyOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine whether a queue with the specified format name exists..
        /// </summary>
        internal static string QueueExistsError {
            get {
                return ResourceManager.GetString("QueueExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string QueueHelp {
            get {
                return ResourceManager.GetString("QueueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access MessageQueue network. Please make sure that the message queuing service is available in your system..
        /// </summary>
        internal static string QueueNetworkProblems {
            get {
                return ResourceManager.GetString("QueueNetworkProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string QueueOk {
            get {
                return ResourceManager.GetString("QueueOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Name.
        /// </summary>
        internal static string RefByFormatName {
            get {
                return ResourceManager.GetString("RefByFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string RefByLabel {
            get {
                return ResourceManager.GetString("RefByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string RefByPath {
            get {
                return ResourceManager.GetString("RefByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reference Queue By:.
        /// </summary>
        internal static string ReferenceLabel {
            get {
                return ResourceManager.GetString("ReferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing message queue {0}..
        /// </summary>
        internal static string RemovingQueue {
            get {
                return ResourceManager.GetString("RemovingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring message queue {0} to previous state..
        /// </summary>
        internal static string RestoringQueue {
            get {
                return ResourceManager.GetString("RestoringQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select message queue:.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender identifier has not been attached to the message..
        /// </summary>
        internal static string SenderIdNotAttached {
            get {
                return ResourceManager.GetString("SenderIdNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender identifier is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string SenderIdNotSet {
            get {
                return ResourceManager.GetString("SenderIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent time is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string SentTimeNotSet {
            get {
                return ResourceManager.GetString("SentTimeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source computer is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string SourceMachineNotSet {
            get {
                return ResourceManager.GetString("SourceMachineNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored object format is not supported by ActiveXMessageFormatter..
        /// </summary>
        internal static string StoredObjectsNotSupported {
            get {
                return ResourceManager.GetString("StoredObjectsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Count limit exceeded ({0})..
        /// </summary>
        internal static string TooManyColumns {
            get {
                return ResourceManager.GetString("TooManyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string toStringNone {
            get {
                return ResourceManager.GetString("toStringNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit or roll back transaction because BeginTransaction has not been called..
        /// </summary>
        internal static string TransactionNotStarted {
            get {
                return ResourceManager.GetString("TransactionNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a transaction while a pending transaction exists..
        /// </summary>
        internal static string TransactionStarted {
            get {
                return ResourceManager.GetString("TransactionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target type array is missing. The target type array must be set in order to deserialize the XML-formatted message..
        /// </summary>
        internal static string TypeListMissing {
            get {
                return ResourceManager.GetString("TypeListMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer does not support the type..
        /// </summary>
        internal static string TypeNotSupported {
            get {
                return ResourceManager.GetString("TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 0x{0} is unknown..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Queuing version is not defined for this message. The message was not created by a call to the Receive method..
        /// </summary>
        internal static string VersionNotSet {
            get {
                return ResourceManager.GetString("VersionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature requires Windows NT..
        /// </summary>
        internal static string WinNTRequired {
            get {
                return ResourceManager.GetString("WinNTRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Formatter.
        /// </summary>
        internal static string XmlFormatter {
            get {
                return ResourceManager.GetString("XmlFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the set of possible types that will be deserialized by the formatter from the message provided..
        /// </summary>
        internal static string XmlMsgTargetTypeNames {
            get {
                return ResourceManager.GetString("XmlMsgTargetTypeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the set of possible types that will be deserialized by the formatter from the message provided..
        /// </summary>
        internal static string XmlMsgTargetTypes {
            get {
                return ResourceManager.GetString("XmlMsgTargetTypes", resourceCulture);
            }
        }
    }
}
