//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.0.2.0")]
[assembly: AssemblyVersion("1.0.2.0")]
[assembly: AssemblyInformationalVersion("1.0.2-alpha.21+Branch.develop.Sha.e666c165f1d14e2473de6b0eef923226aec4ddda")]
